# Generated by Django 4.0.3 on 2022-03-19 05:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_alter_comment_edited_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at', '-edited_at', 'author', 'id')},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at', '-updated_at', 'title', 'author')},
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 11, 27, 23, 797343)),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
